# Generated by Django 3.2 on 2022-08-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_date',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
    ]
