# Generated by Django 3.2 on 2022-08-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('file', models.FileField(upload_to='files/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
