# Generated by Django 3.2 on 2022-08-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='author',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
