# Generated by Django 3.2 on 2022-08-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(default='test', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
