# Generated by Django 3.2 on 2022-08-15 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printable', '0002_file_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='id',
            new_name='uuid',
        ),
    ]
