# Generated by Django 3.2 on 2022-08-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printable', '0003_rename_id_file_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='uuid',
            new_name='file_id',
        ),
    ]
