# Generated by Django 3.2 on 2022-08-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printable', '0003_file_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
