# Generated by Django 3.2 on 2022-08-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printable', '0004_file_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
