# Generated by Django 3.2 on 2022-08-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printable', '0005_alter_file_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='file/'),
        ),
    ]
