# Generated by Django 3.2 on 2022-08-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_orderlineitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='original_bag',
            new_name='original_shopping_cart',
        ),
    ]
