# Generated by Django 3.2 on 2022-07-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_patterns',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_sizes',
        ),
    ]
