# Generated by Django 3.2 on 2022-08-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220808_1146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
