# Generated by Django 3.2.15 on 2022-08-17 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='wishlist',
        ),
    ]
